# Redirect domain aliases to primary domain
https://www.bonnet.cl/* https://enbonnet.me/:splat 301!
https://bonnet.cl/* https://enbonnet.me/:splat 301!

# These extra rules are required because HTTPS is not forced
http://www.bonnet.cl/* https://enbonnet.me/:splat 301!
http://bonnet.cl/* https://enbonnet.me/:splat 301!

# Optional: Redirect default Netlify subdomain to primary domain
https://zen-euclid-39eefb.netlify.com/* https://enbonnet.me/:splat 301!
http://zen-euclid-39eefb.netlify.com/* https://enbonnet.me/:splat 301!